### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by ghost** [donmaiq/Mpv-Playlistmanager#39] opened 2020-05-03 12:16 UTC
After dragging a file to mpv other files in folder not showing in playlist.

**Comment by jonniek** [comment] 2020-05-03 16:53
Could you share a sample directory and file structure and steps to reproduce the issue more specifically.

**Comment by ghost** [comment] 2020-05-03 17:43
Steps to reproduce:
1- Open a random folder that contains more than 1 file
2- Open mpv
3- Drag file to mpv
4- Press playlist key
5- Only the dragged file will appear in playlist
normal playlist [https://i.imgur.com/pDQsv3l.png](https://i.imgur.com/pDQsv3l.png)
dragged file's playlist [https://i.imgur.com/TB8P16i.png](https://i.imgur.com/TB8P16i.png)
folder view [https://i.imgur.com/JdKT4yz.png](https://i.imgur.com/JdKT4yz.png)

**Comment by jonniek** [comment] 2020-05-03 17:51
Hmm I couldn't reproduce the issue.

Could you open mpv from command line, reproduce the issue and see if there is any messages from playlistmanager.

On windows you can open powershell and run `mpv --idle --force-window`. You might need to `cd $mpv_dir` first if your mpv exe is not added to path.

**Comment by ghost** [comment] 2020-05-03 17:56
Its normally work with commandline. Just dragging causes this issue. Its not big issue for me, I just wanted to report it.

**Comment by jonniek** [comment] 2020-05-04 09:15
With dragging do you mean dragging and dropping the file on the mpv.exe?

Could you add `--log-file=C:\some_path\mpv.log` to your mpv.conf, reproduce the issue and paste the logfile here or pastebin.

**Comment by ghost** [comment] 2020-05-04 09:41
[https://pastebin.com/NL8hL21s](https://pastebin.com/NL8hL21s)
I mean dragging a file to mpv player's window

**Comment by CogentRedTester** [comment] 2020-05-04 10:56
So the problem here is that you're dragging a file onto mpv, and it's not loading other files in the directory? That is the normal behaviour of mpv unless you're using autoload.lua or using the autoload functionality of this script which is under the option loadfiles_on_start, or with the hotkey (P by default).

Is the problem with the autoload function of this script?

**Comment by CogentRedTester** [comment] 2020-05-04 10:59
I can actually reproduce this issue. If you open the mpv window in idle mode with force-window=yes, then drag a file into the mpv window, then it will not autoload the folder even with `loadfiles_on_start=yes`

**Comment by CogentRedTester** [comment] 2020-05-04 11:02
I believe this is because the script checks the loadfiles setting immediately after being loaded, but when launched in idle mode the playlist is empty, so it doesn't do anything. Then, because that part of the code is not triggered by any events, loading a single file afterwards does nothing.

This can probably be fixed by just moving that if statement into a start-file event, or into the existing on_load function

**Comment by jonniek** [comment] 2020-05-04 11:28
Oh I see the issue now. That feature was designed to only be ran once. However, I guess if the idle load found 0 from working dir then it could fallback to loading on first load event.

**Comment by jonniek** [comment] 2020-05-04 11:34
A quick fix: 7046ce28385cb4eeda0d7ed78371b9860b08a6f5

This should be pretty harmless update. Running playlist loading on every file load event would need some other updates to avoid getting duplicate files etc.

**Comment by CogentRedTester** [comment] 2020-05-04 11:38
It might not be so bad to load it on each file load event if you only do it when the playlist count is 1. That would mean it doesn't do anything when moving around inside the same playlist, and if you replace the playlist with a new file it'd auto load the files in that directory

**Comment by jonniek** [comment] 2020-05-04 11:49
That's a good idea. It works very nicely with some quick testing 034b2051426dcbb5d9344ede34607e92ecfa169a

**Comment by CogentRedTester** [comment] 2020-05-04 12:41
Seems to be working on my end as well.

**Closed as completed** 2020-05-04 14:26 UTC
