### ISSUE TITLE
page move down or up does not work

### ISSUE THREAD

**Issue by ghost** [donmaiq/Mpv-Playlistmanager#115] opened 2023-01-06 22:09 UTC
title say as it

**Comment by jonniek** [comment] 2023-01-07 04:34
By not work do you mean nothing happens?

For me it moves up or down by the `showamount` which I assume was expected behaviour of the person who implemented it.

It has a weird effect when playlist is sliced from beginning and end though. Since the selection is in the middle and the logical page down would be `ceiling(showamount / 2)` for `showamount` of odd numbers. Is this what you would expect?

For example:

```
  ...
  File10
  File11
->File12
  File13
  File14
  ...
```
Would you expect page up and down to always jump to the next file in `...`?

**Comment by ghost** [comment] 2023-01-07 04:43
Ah I guess I misunderstood, my expectation was that I couldn't see which video to select because the list didn't fit on the screen, so I thought we were going to use pg down to bring that list down, fortunately I solved the problem by changing the size of the font, thank you for the help

**Comment by jonniek** [comment] 2023-01-07 05:04
Yeah that's an annoying issue. I brought down the default showamount as a quick fix d43619d0b6612e78d12cd271e17c2fb77962109d with some improvements to the rendering logic.

There is a duplicate #106 so I'll close this one.

**Closed as completed by jonniek** 2023-01-07 05:04 UTC

**Comment by tupo2** [comment] 2023-01-07 10:33
For me, with the last commit it only shows 8 entries instead of 9 by default.

**Comment by jonniek** [comment] 2023-01-09 03:58
> For me, with the last commit it only shows 8 entries instead of 9 by default.

I changed it to count the `...`. This way the playlist will always be at most `showamount` lines long instead of sometimes growing and shrinking.
