### ISSUE TITLE
Showing Youtube Title

### ISSUE THREAD

**Issue by mortyobnoxious** [donmaiq/Mpv-Playlistmanager#15] opened 2019-04-25 15:22 UTC
On Youtube playlists, is it possible to show the title of each video instead of url?

![image](https://user-images.githubusercontent.com/42044258/56747629-fed28980-6786-11e9-9b1b-bd4b214c3c30.png)

**Comment by jonniek** [comment] 2019-04-26 06:44
This is currently not possible unless you load a youtube playlist(list=id url). I tried some implementation of this by fetching titles but it wasn't clean enough in my opinion.

That said, i think this is a very desirable feature and I hope it's possible in the future. I will try to think of some clean solution unless it will be implemented in mpv itself.

**Comment by mortyobnoxious** [comment] 2019-04-26 07:57
**Youtube-dl** provides titles if i'm not mistaken as in picture below. Maybe, fetching titles through Youtube-dl would be possible.

![image](https://user-images.githubusercontent.com/42044258/56792249-db085580-6811-11e9-9d56-675e998ca0d0.png)

**Comment by jonniek** [comment] 2019-04-26 15:54
I tried it and it's quite trivial to fetch the title with youtube-dl. The problem is it blocks mpv for a few seconds and just feels laggy. I don't see any easy solution to work around this sync problem in a os agnostic way.

**Comment by jonniek** [comment] 2019-04-30 17:00
Hi,

I hacked together a solution for this for windows. It's quick and dirty so I decided to make it a separate file to not make the messy large codebase even bigger mess. The playlistmanager file has to be updated as well to be able to receive the urls.

I tried to make it work on unix but I had trouble with the subprocess escaping my commands. I have a workaround in my gist https://gist.github.com/jonniek/483f591bb2432051346a8e564595896e
The workaround uses a helper script to do the fetching and formatting. I haven't tried it yet but it should work.

I will leave this issue open until I have a standalone lua file for unix as well.

**Comment by wjtk4444** [comment] 2019-07-04 12:02
Here's my multithreaded (1 script resolves, other displays) solution for resolving titles using youtube-dl.

Here's the part that actually does something:
```{.lua}
local res = io.popen('youtube-dl --flat-playlist -sJ '..
    filename):read("*all")
local json, err = utils.parse_json(res)
local playlist = json['_type'] and json['_type'] == 'playlist'
local title = (playlist and '[playlist]: ' or '') .. json['title']
```

And a full resolver script if anyone's interested:
```{.lua}
local mp = require 'mp'
local utils = require 'mp.utils'

mp.register_script_message("ytdl_resolve_title", function(filename)
        -- debug message
        -- print('started resolving title for:', filename)
        
        -- title cannot be resolved using youtube-dl
        if not string.match(filename, "^https?://") then
            -- print('not a network resource')
            return
        end

        local res = io.popen('youtube-dl --flat-playlist -sJ '..
            filename):read("*all")
        local json, err = utils.parse_json(res)
        if err then
            -- print('error parsing json')
            return
        else 
            local playlist = json['_type'] and json['_type'] == 'playlist'
            local title = (playlist and '[playlist]: ' or '') .. json['title']
            mp.commandv('script-message', 'osc_update_title', filename, title)
        end
            
        -- print('finished resolving title for:', filename)
    end)
```

**Comment by jonniek** [comment] 2019-07-04 17:45
Seems to work with some quick tests, I didn't realize separating the files already fixes the sync problem. I will take a deeper look at it later and see if I can use it.

**Comment by jonniek** [comment] 2019-07-21 13:30
@wjtk4444 Thanks to your input I have now updated playlistmanager to resolve urls in platform independent way. Windows doesn't support unicode like usual so I will still keep the previous windows script in the repository. If you have any problems with the new `titleresolver.lua` script feel free to open a new issue.

**Comment by wjtk4444** [comment] 2019-07-21 22:57
> Windows doesn't support unicode like usual so I will still keep the previous windows script in the repository.

I remember seeing some poweshell shenanigans somewhere, maybe look at [this](https://github.com/Eisa01/mpv-scripts/tree/master/scripts), especially [here](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SmartCopyPaste-II-1.5.lua#L37-L59)

It *should* work, I think. It's been a while since I tinkered with mpv on windows though, so you'll have to try and see yourself.

**Comment by jonniek** [comment] 2019-07-22 06:58
Yeah powershell can do it for sure. Right now It's writing it to a file in utf8 but it would be more efficient to just read the stdout. I'll take a look and update the windows script later.

**Comment by jonniek** [comment] 2019-07-22 17:24
So it seems like the Windows version didn't work after all. I'm convinced powershell and windows in general is trash so I will not waste any more energy on this. Feel free to tinker with it though.

Progress so far, unicode not working. I tried half a dozen different ways of outputting but no luck.
```lua
local utils = require("mp.utils")
mp.register_script_message("geturltitle", function(filename)
  local args = {
    'powershell', '-NoProfile', '-Command', [[& {
        Trap {
            Write-Error -ErrorRecord $_
            Exit 1
        }
        $OutputEncoding = New-Object -typename System.Text.UTF8Encoding
        $title = youtube-dl --get-title "]]..filename..[["
        $data = [system.Text.Encoding]::UTF8.GetBytes($title)
        [Console]::OpenStandardOutput().Write($data, 0, $data.Length)
    }]]
  }
  local res = utils.subprocess({args=args})
  local title = res.stdout
  if title ~= '' then
    mp.commandv('script-message', 'playlistmanager', 'addurl', filename, title)
  end
end)
```

youtbe-dl seems to return unicode but storing it in a variable or outputting seems to converts it to a non utf8 string.

**Comment by wjtk4444** [comment] 2019-07-22 22:34
Sorry for not so much an actual answer, but I booted windows to check what's up and it seems that my script posted a few comments above works perfectly fine with UTF-8 (I'm assuming that's utf-8). On windows 7, without powershell, temporary files or anything else.

EDIT:
Freshly downloaded mpv (shinichiro build) and youtube-dl.

![Capture](https://user-images.githubusercontent.com/20820296/61669699-7e152200-acd0-11e9-9646-188858544074.PNG)

**Comment by jonniek** [comment] 2019-07-23 16:12
Thanks for the sanity check.

I got worried it was just some problem on my system but your script worked for me. For some reason unicode doesn't work with the `--get-title` parameter on windows but the json dump works. I'm not sure if the bug is in youtube-dl, mpv or windows and I'm **not** going to find out.

Thanks again for the help! I updated my script to use the json dump.

**Comment by gbstan** [comment] 2019-07-23 17:16
I have been trying this on various youtube (playlist) links but I only ever get 1 single item in the playlist. The title of the item is displayed correctly, which seems to indicate that the script works.

Could you please provide an example, e.g. mpv [youtube URL] that allows to test the playlist functionality with more than 1 item in the playlist.

**Comment by jonniek** [comment] 2019-07-23 17:38
I just notice a big bug my style refactoring caused 2a4dae1285d15d55803f6ab521cea70773a16536

This might be unrelated to your problem but I think ytdl is supposed to resolve playlist urls. I noticed some urls work and some do not. But I still get all the urls in the playlist regardless if they get resolved to titles or not.

This one doesn't seem to work: https://www.youtube.com/watch?list=RDQMY9fb3d5ussU
But this one does seem to work: https://www.youtube.com/watch?list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10

**Comment by wjtk4444** [comment] 2019-07-23 18:21
```{.md}
--no-playlist                    Download only the video, if the URL refers
                                 to a video and a playlist.
--yes-playlist                   Download the playlist, if the URL refers to
                                 a video and a playlist.
```
From [ytdl readme](https://github.com/ytdl-org/youtube-dl/blob/master/README.md)

**Comment by gbstan** [comment] 2019-07-23 19:43
Yes, I confirm that it now works. However the first link indeed doesn't work fully: https://www.youtube.com/watch?list=RDQMY9fb3d5ussU
Some titles are there and some other are not (URLs instead), the URLs are slowly and iteratively replaced by the titles.
So, for some reason, youtube-dl doesn't get all the titles. Maybe this should be checked with and reported back to youtube-dl/ytdl.

**Comment by wjtk4444** [comment] 2019-07-23 19:50
I think those are the (only two?) valid youtube url schemas that point out to a playlist. The urls you posted @gbstan and @jonniek aren't working for me even in the web browser.
`https://www.youtube.com/playlist?list=PLAYLIST_ID`
`https://www.youtube.com/watch?v=VIDEO_ID&list=PLAYLIST_ID`

**Comment by gbstan** [comment] 2019-07-23 19:54
I suggest some safeguarding in the code. I have detected some edge cases that can break the code.
Here are the suggestions:

**local function isempty(s)
  return s == nil or s == ''
end**

mp.observe_property('playlist-count', "number", function()
  if playlist_visible then showplaylist() end

  -- code to resolve url titles
  local length = mp.get_property_number('playlist-count', 0)
  if length < 2 then return end
  local i=0
  -- loop all items in playlist because we can't predict how it has changed
  while i < length do
    local filename = mp.get_property('playlist/'..i..'/filename')
    local title = mp.get_property('playlist/'..i..'/title')
    **if isempty(filename) then
      filename = "==="
    end**
    if filename:match('^https?://')
      and not title
      and not url_table[filename]
      and not requested_urls[filename]
    then
      requested_urls[filename] = true
      mp.commandv('script-message', 'resolveurltitle', filename)
    end
    i=i+1
  end
end)

**Comment by gbstan** [comment] 2019-07-23 19:58
How do you find the youtube playlist URLs? I am trying to search on youtube for playlist but somehow what I get is not of the format @wjtk4444 is mentioning.

**Comment by wjtk4444** [comment] 2019-07-23 20:07
Click on any channel, then look at the playlist section. By clicking on the playlist image you'll go to `/watch?v=VIDEO_ID&list=PLAYLIST_ID`. If you click the playlist title instead, you'll go directly to the playlist view (`/playlist?list=PLAYLIST_ID`).

You can switch the views by clicking either any video or the playlist title on the top.
![image](https://user-images.githubusercontent.com/20820296/61743667-4a480400-ad85-11e9-8606-d661aa00b0ce.png)

**Comment by gbstan** [comment] 2019-07-23 20:28
Got it! Thank you!

**Comment by jonniek** [comment] 2019-07-23 21:05
I see there has been some changes to youtube playlist since i last looked at them. It seems like @wjtk4444 earlier code snippet handles playlist quite nicely, I didn't know what the playlist logic was doing earlier but it makes sense now. Fixed resolver again.

The only case where it doesn't work as expected could be ?v=asd&list=fgs urls that get resolved to the playlist name rather than video name. I'll investigate more tomorrow.

**Comment by mortyobnoxious** [comment] 2019-07-25 17:33
Hi, @jonniek. 
When i open a [url](https://www.youtube.com/playlist?list=PLo3w8EB99pqLEopnunz-dOOBJ8t-Wgt2g) through mpv **directly** and then right-click the triangle i pointed on picture below, it shows titles of the playlist as expected.
![image](https://user-images.githubusercontent.com/42044258/61895059-67faa200-af1a-11e9-9778-c6b4ad9a2322.png)

But after i save it as playlist to desktop as in picture below and open playlist from desktop, then right-click it doesn't show titles.
![image](https://user-images.githubusercontent.com/42044258/61895137-99736d80-af1a-11e9-9d7f-7799f1b9c871.png)

**Comment by jonniek** [comment] 2019-07-25 18:59
Ytdl only resolves titles when opening the playlist url. When we save the playlist the original playlist url is not available for us any longer so we can't load it. The only way to get the titles is to manually fetch every single one from the url. The current behavior in playlistmanager will do this but it seems to load them rather slowly at around 1-2 seconds per title in synchronously.

If you want to save the playlist url only you need to save before it has been resolved by ytdl or creating the playlist file manually with just the url:
```
https://www.youtube.com/playlist?list=PLo3w8EB99pqLEopnunz-dOOBJ8t-Wgt2g
```

**Comment by mortyobnoxious** [comment] 2019-07-25 20:43
When i save the url below as m3u playlist. It doesn't work. It doesn't open it with mpv. I don't know why.
`https://www.youtube.com/playlist?list=PLo3w8EB99pqLEopnunz-dOOBJ8t-Wgt2g`

Saving it like this works but can't see titles.:
```
https://youtu.be/O_GWbkXIqEY
https://youtu.be/PORRrz3Y8Vc
https://youtu.be/Y02yI1OfZjI
https://youtu.be/09XmbByy6Sk
https://youtu.be/hA7ESX7FsE4
https://youtu.be/uE3UPEK26U0
```

But saving playlist url as **batch(.bat)** file with the code below works. I guess i will use this.
`start mpv.exe https://www.youtube.com/playlist?list=PLo3w8EB99pqLEopnunz-dOOBJ8t-Wgt2g`


So this is going to be somewhat out of place but is it possible use playlistmanager's **saveplaylist** option to save playlists like this if it is a youtube url (using m3u syntax):

```
#EXTINF:, What is "The Web" and how does it work?
https://www.youtube.com/watch?v=O_GWbkXIqEY
#EXTINF:, What's HTML and how does it work?
https://www.youtube.com/watch?v=PORRrz3Y8Vc
etc.
```

This will also save the titles.

**Comment by jonniek** [comment] 2019-07-26 07:14
Sorry I didn't actually check if the playlist url opens from a playlist similarly to command line. Seems like it might skip the ytdl playlist resolving and behave similar to appending the url to playlist.

> `#EXTINF:, What is "The Web" and how does it work?`

This looks super convenient. It should be no problem to save this metadata in the m3u. I will implement later today!

**Comment by mortyobnoxious** [comment] 2019-07-26 09:39
thank you.

**Comment by jonniek** [comment] 2019-07-26 16:26
@mortyobnoxious  added titles to m3u 60dbc653ced2ccc9c295b7b25299768be4a2ecf9

Also added `--no-playlist` to the resolver as it seems to fix that earlier problematic filename I mentioned. @wjtk4444 is always 2 steps ahead of me it seems. I'm not sure if there is any way to read if the user has set the ytld-raw-options=yes-playlist so it might break in that case, I'll dig in to that if anyone encounters problems with it.

**Closed as completed** 2019-07-31 13:10 UTC

**Comment by FichteFoll** [comment] 2020-01-05 16:15
Can probably be unpinned?
